# Generated by Django 3.0.1 on 2021-12-29 10:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=40, null=True)),
                ('SKU', models.CharField(max_length=40, unique=True)),
                ('Size', models.CharField(blank=True, max_length=40, null=True)),
                ('Color', models.CharField(blank=True, max_length=40, null=True)),
                ('Description', models.CharField(blank=True, max_length=40, null=True)),
                ('Price', models.FloatField(blank=True, null=True)),
                ('Category', models.CharField(blank=True, choices=[('earrings', 'Earrings'), ('objet dart', "objet d'art"), ('rings', 'Rings'), ('necklaces', 'Necklaces')], default='earrings', max_length=30, null=True)),
                ('Status', models.CharField(blank=True, choices=[('active', 'Active'), ('disabled', 'Disabled')], default='Active', max_length=30, null=True)),
                ('Optional', models.CharField(blank=True, choices=[('best seller', 'Best Seller'), ('new arrivals', 'New Arrivals'), ('on sale', 'On Sale')], default='new arrivals', max_length=30, null=True)),
                ('Image', models.ImageField(blank=True, null=True, upload_to='static/images')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Comment', models.CharField(max_length=40)),
                ('OrderNumber', models.IntegerField(unique=True)),
                ('Customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('Item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='MA.Product')),
            ],
        ),
    ]
