# Generated by Django 3.2.9 on 2021-12-26 23:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SKU', models.CharField(max_length=40, unique=True)),
                ('Size', models.CharField(max_length=40)),
                ('Color', models.CharField(max_length=40)),
                ('Description', models.CharField(max_length=40)),
                ('Price', models.FloatField()),
                ('Category', models.CharField(choices=[('earrings', 'Earrings'), ('objet dart', "objet d'art"), ('rings', 'Rings'), ('necklaces', 'Necklaces')], default='earrings', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Comment', models.CharField(max_length=40)),
                ('OrderNumber', models.IntegerField(unique=True)),
                ('Customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('Item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='MA.item')),
            ],
        ),
    ]
