# Generated by Django 3.0.1 on 2021-12-29 13:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MA', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='Customer',
            new_name='User',
        ),
        migrations.RemoveField(
            model_name='order',
            name='Comment',
        ),
        migrations.RemoveField(
            model_name='order',
            name='Item',
        ),
        migrations.RemoveField(
            model_name='order',
            name='OrderNumber',
        ),
        migrations.AddField(
            model_name='order',
            name='Being_delivered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='Ordered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='Ordered_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='Received',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='Ref_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='Start_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ordered', models.BooleanField(default=False)),
                ('Quantity', models.IntegerField(default=1)),
                ('Item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MA.Product')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Street_address', models.CharField(max_length=100)),
                ('Apartment_address', models.CharField(max_length=100)),
                ('Country', django_countries.fields.CountryField(max_length=2)),
                ('Zip', models.CharField(max_length=100)),
                ('Default', models.BooleanField(default=False)),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Addresses',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='Items',
            field=models.ManyToManyField(to='MA.OrderItem'),
        ),
        migrations.AddField(
            model_name='order',
            name='Shipping_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='MA.Address'),
        ),
    ]
