# Generated by Django 3.0.1 on 2021-12-29 13:25

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MA', '0002_auto_20211229_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Size',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=10, null=True), blank=True, null=True, size=None),
        ),
    ]
