# Generated by Django 3.2.9 on 2021-12-27 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MA', '0002_auto_20211227_0146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='Category',
            field=models.CharField(blank=True, choices=[('earrings', 'Earrings'), ('objet dart', "objet d'art"), ('rings', 'Rings'), ('necklaces', 'Necklaces')], default='earrings', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='Color',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='Price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='Size',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='Status',
            field=models.CharField(blank=True, choices=[('active', 'Active'), ('disabled', 'Disabled')], default='Active', max_length=30, null=True),
        ),
    ]
