# Generated by Django 3.2.9 on 2021-12-27 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MA', '0003_auto_20211227_0307'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Item',
            new_name='Product',
        ),
    ]
