# Generated by Django 3.2.9 on 2021-12-27 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MA', '0004_rename_item_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Name',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
