# Generated by Django 3.0.1 on 2021-12-30 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MA', '0007_auto_20211230_0803'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='Items',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='Order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MA.Order'),
        ),
    ]
