# Generated by Django 3.0.1 on 2021-12-30 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MA', '0008_auto_20211230_0809'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='Items',
            field=models.ManyToManyField(to='MA.OrderItem'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='Customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='MA.Customer'),
        ),
    ]
