# Generated by Django 3.0.1 on 2021-12-31 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MA', '0009_auto_20211230_0935'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='Items',
        ),
        migrations.AlterField(
            model_name='order',
            name='Start_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
