# Generated by Django 3.0.1 on 2021-12-31 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MA', '0010_auto_20211231_0921'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='Items',
            field=models.ManyToManyField(to='MA.OrderItem'),
        ),
    ]
