# Generated by Django 3.0.1 on 2022-01-01 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MA', '0011_order_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='Items',
        ),
    ]
