# Generated by Django 3.0.1 on 2022-01-01 08:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('MA', '0012_remove_order_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='Ref_code',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
