# Generated by Django 3.0.1 on 2022-01-01 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MA', '0013_auto_20220101_0826'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='User',
        ),
        migrations.AddField(
            model_name='address',
            name='Customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='MA.Customer'),
        ),
        migrations.AddField(
            model_name='order',
            name='Total',
            field=models.FloatField(default=0),
        ),
    ]
