# Generated by Django 3.0.1 on 2022-01-01 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MA', '0014_auto_20220101_0848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='Total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
