# Generated by Django 3.0.1 on 2022-01-04 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MA', '0015_auto_20220101_0850'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discover',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(blank=True, max_length=40, null=True)),
                ('Image1', models.ImageField(blank=True, null=True, upload_to='static/images')),
                ('Image2', models.ImageField(blank=True, null=True, upload_to='static/images')),
                ('Image3', models.ImageField(blank=True, null=True, upload_to='static/images')),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='Total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='product',
            name='Discover',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MA.Discover'),
        ),
    ]
