# Generated by Django 3.0.1 on 2022-01-04 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MA', '0016_auto_20220104_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='discover',
            name='Items',
            field=models.ManyToManyField(to='MA.Product'),
        ),
    ]
