# Generated by Django 3.0.1 on 2022-01-05 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MA', '0017_discover_items'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['Ordered']},
        ),
    ]
