# Generated by Django 3.0.1 on 2022-01-05 06:56

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MA', '0018_auto_20220105_0650'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-Ordered']},
        ),
        migrations.AddField(
            model_name='product',
            name='Images',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.ImageField(blank=True, null=True, upload_to='static/images'), blank=True, null=True, size=None),
        ),
    ]
