# Generated by Django 3.0.1 on 2022-01-05 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MA', '0019_auto_20220105_0656'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Images',
        ),
    ]
