# Generated by Django 3.0.1 on 2022-01-05 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MA', '0021_auto_20220105_0703'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Images',
        ),
        migrations.AddField(
            model_name='picture',
            name='Product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MA.Product'),
        ),
    ]
