# Generated by Django 3.0.1 on 2022-01-06 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MA', '0023_auto_20220106_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='Ref_code',
            field=models.CharField(default='22010660RW', max_length=40, unique=True),
        ),
    ]
