# Generated by Django 3.0.1 on 2022-01-07 09:30

from django.db import migrations, models
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('MA', '0026_auto_20220107_0910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='Ref_code',
            field=models.CharField(default='2201075ZDE', max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='Total',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default_currency='USD', max_digits=14, null=True),
        ),
    ]
