# Generated by Django 3.0.1 on 2022-01-07 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MA', '0027_auto_20220107_0930'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='Ref_code',
        ),
    ]
