# Generated by Django 3.0.1 on 2022-01-07 10:40

from django.db import migrations
import shortuuidfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('MA', '0028_remove_order_ref_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='Ref_code',
            field=shortuuidfield.fields.ShortUUIDField(blank=True, editable=False, max_length=22),
        ),
    ]
