# Generated by Django 3.0.1 on 2022-01-08 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MA', '0029_order_ref_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='Ordered',
            new_name='Done',
        ),
        migrations.AlterField(
            model_name='address',
            name='Apartment_address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='Default',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='Street_address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='Zip',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='Description',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
