# Generated by Django 3.0.1 on 2022-03-14 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MA', '0030_auto_20220108_1030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='Customer',
        ),
    ]
