# Generated by Django 3.0.1 on 2022-03-14 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MA', '0031_remove_address_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='Shipping_address',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='MA.Address'),
        ),
    ]
