# Generated by Django 3.0.1 on 2022-03-14 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MA', '0035_auto_20220314_1102'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Money',
            new_name='PriceLBP',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Money_currency',
            new_name='PriceLBP_currency',
        ),
    ]
