# Generated by Django 4.0.4 on 2022-05-18 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MA', '0040_alter_address_id_alter_customer_id_alter_discover_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Description',
            field=models.TextField(blank=True, max_length=400, null=True),
        ),
    ]
