# Generated by Django 4.0.4 on 2022-10-11 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MA', '0042_rename_being_delivered_order_shipped'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='Received',
            new_name='Delivered',
        ),
        migrations.AddField(
            model_name='order',
            name='Delivered_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='Shipped_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
