# Generated by Django 4.0.4 on 2022-10-16 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MA', '0047_alter_order_ref_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='Ref_code',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
    ]
