# Generated by Django 4.0.4 on 2022-10-18 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MA', '0048_alter_order_ref_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, editable=False, max_length=200, null=True)),
                ('Email', models.EmailField(blank=True, editable=False, max_length=254, null=True)),
                ('Content', models.TextField(blank=True, null=True)),
                ('Response', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
