# Generated by Django 4.0.4 on 2022-10-22 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MA', '0049_contactus'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Pick',
            field=models.BooleanField(default=False),
        ),
    ]
