# Generated by Django 4.0.4 on 2022-10-24 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MA', '0051_alter_contactus_options_collection_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discover',
            old_name='Image1',
            new_name='Image',
        ),
        migrations.RemoveField(
            model_name='discover',
            name='Image2',
        ),
        migrations.RemoveField(
            model_name='discover',
            name='Image3',
        ),
        migrations.AddField(
            model_name='discover',
            name='Active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='discover',
            name='Description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='discover',
            name='Title',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
