# Generated by Django 4.0.4 on 2022-10-29 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MA', '0052_rename_image1_discover_image_remove_discover_image2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Category',
            field=models.CharField(blank=True, choices=[('earrings', 'earrings'), ('objet dart', "objet d'art"), ('rings', 'rings'), ('necklaces', 'necklaces')], default='earrings', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='Status',
            field=models.CharField(blank=True, choices=[('active', 'Active'), ('disabled', 'Disabled')], default='active', max_length=30, null=True),
        ),
    ]
