# Generated by Django 4.0.4 on 2022-11-02 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MA', '0054_zones'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Zones',
            new_name='Zone',
        ),
    ]
