# Generated by Django 4.0.4 on 2022-11-02 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MA', '0055_rename_zones_zone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zone',
            name='Zone',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
