# Generated by Django 4.0.4 on 2022-11-03 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MA', '0057_country'),
    ]

    operations = [
        migrations.RenameField(
            model_name='zone',
            old_name='Zone',
            new_name='ZoneNumber',
        ),
    ]
