# Generated by Django 4.0.4 on 2022-11-03 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MA', '0058_rename_zone_zone_zonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='Zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MA.zone'),
        ),
    ]
