# Generated by Django 4.0.4 on 2022-11-04 10:46

import MA.utils
import colorfield.fields
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MA', '0060_alter_country_country'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactus',
            options={'verbose_name': 'Contact Us', 'verbose_name_plural': 'Contact Us'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name': 'Country', 'verbose_name_plural': 'Countries'},
        ),
        migrations.AlterField(
            model_name='country',
            name='Country',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='Color',
            field=django.contrib.postgres.fields.ArrayField(base_field=colorfield.fields.ColorField(default='#FF0000', image_field=None, max_length=18, samples=None), blank=True, default=MA.utils.get_default_color, null=True, size=None),
        ),
    ]
