# Generated by Django 4.0.4 on 2022-11-04 11:21

import MA.utils
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MA', '0062_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Color',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=30, null=True), blank=True, default=MA.utils.get_default_color, null=True, size=None),
        ),
    ]
