# Generated by Django 4.0.4 on 2022-11-05 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MA', '0064_product_colorhex'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.EmailField(blank=True, max_length=254, null=True)),
                ('Name', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'Newsletter',
                'verbose_name_plural': 'Newsletters',
            },
        ),
    ]
