# Generated by Django 4.0.4 on 2022-11-06 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MA', '0065_newsletter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='Name',
            new_name='Fist_name',
        ),
        migrations.AddField(
            model_name='customer',
            name='Last_name',
            field=models.CharField(blank=True, editable=False, max_length=200, null=True),
        ),
    ]
