# Generated by Django 4.0.4 on 2022-11-06 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MA', '0066_rename_name_customer_fist_name_customer_last_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='Fist_name',
            new_name='First_name',
        ),
    ]
