# Generated by Django 4.0.4 on 2022-11-08 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MA', '0071_alter_collection_image_alter_discover_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='Title_en',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
