# Generated by Django 4.1.3 on 2022-11-09 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MA", "0072_collection_title_en"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newsletter",
            name="Email",
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="Category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("earrings", "Earrings"),
                    ("objet dart", "Objet d'art"),
                    ("rings", "Rings"),
                    ("necklaces", "Necklaces"),
                ],
                default="Earrings",
                max_length=30,
                null=True,
            ),
        ),
    ]
