# Generated by Django 4.1.3 on 2022-11-09 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MA", "0073_alter_newsletter_email_alter_product_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Name", models.CharField(blank=True, max_length=120, null=True)),
                (
                    "Display_name",
                    models.CharField(blank=True, max_length=120, null=True),
                ),
            ],
        ),
    ]
