# Generated by Django 4.1.3 on 2022-11-09 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("MA", "0074_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="Category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="MA.category",
            ),
        ),
    ]
