# Generated by Django 4.1.3 on 2022-11-10 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MA", "0076_alter_category_options_remove_collection_items_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="discover",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
