# Generated by Django 4.1.3 on 2022-11-15 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MA", "0079_product_thumbnail_alter_collection_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="Additional_comments",
            field=models.TextField(blank=True, null=True),
        ),
    ]
