# Generated by Django 4.1.3 on 2022-11-15 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MA", "0080_product_additional_comments"),
    ]

    operations = [
        migrations.RemoveField(model_name="product", name="Additional_comments",),
        migrations.AddField(
            model_name="order",
            name="Additional_comments",
            field=models.TextField(blank=True, null=True),
        ),
    ]
