# Generated by Django 4.1.3 on 2022-11-12 21:52

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('MA', '0081_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='Image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=75, scale=None, size=[1920, 1080], upload_to='images'),
        ),
        migrations.AlterField(
            model_name='discover',
            name='Image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=75, scale=None, size=[1920, 1080], upload_to='images'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='picture',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=75, scale=None, size=[1920, 1080], upload_to='images'),
        ),
        migrations.AlterField(
            model_name='product',
            name='Thumbnail',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=40, scale=25, size=[1920, 1080], upload_to='images'),
        ),
    ]
