# Generated by Django 4.1.3 on 2022-11-17 12:03

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ("MA", "0081_remove_product_additional_comments_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="discover",
            name="ImageMobile",
            field=django_resized.forms.ResizedImageField(
                blank=True,
                crop=None,
                force_format="WEBP",
                keep_meta=True,
                null=True,
                quality=100,
                scale=None,
                size=[1920, 1080],
                upload_to="images",
            ),
        ),
        migrations.AlterField(
            model_name="collection",
            name="Image",
            field=django_resized.forms.ResizedImageField(
                blank=True,
                crop=None,
                force_format="WEBP",
                keep_meta=True,
                null=True,
                quality=75,
                scale=None,
                size=[1920, 1080],
                upload_to="images",
            ),
        ),
        migrations.AlterField(
            model_name="discover",
            name="Image",
            field=django_resized.forms.ResizedImageField(
                blank=True,
                crop=None,
                force_format="WEBP",
                keep_meta=True,
                null=True,
                quality=100,
                scale=None,
                size=[1920, 1080],
                upload_to="images",
            ),
        ),
        migrations.AlterField(
            model_name="picture",
            name="picture",
            field=django_resized.forms.ResizedImageField(
                blank=True,
                crop=None,
                force_format="WEBP",
                keep_meta=True,
                null=True,
                quality=75,
                scale=None,
                size=[1920, 1080],
                upload_to="images",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="Image",
            field=django_resized.forms.ResizedImageField(
                blank=True,
                crop=None,
                force_format="WEBP",
                keep_meta=True,
                null=True,
                quality=75,
                scale=None,
                size=[1920, 1080],
                upload_to="images",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="Thumbnail",
            field=django_resized.forms.ResizedImageField(
                blank=True,
                crop=None,
                force_format="WEBP",
                keep_meta=True,
                null=True,
                quality=40,
                scale=25,
                size=[1920, 1080],
                upload_to="images",
            ),
        ),
    ]
