# Generated by Django 4.1.3 on 2022-11-17 16:31

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ("MA", "0082_discover_imagemobile_alter_collection_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="discover",
            name="ImageMobile",
            field=django_resized.forms.ResizedImageField(
                blank=True,
                crop=None,
                force_format="JPEG",
                keep_meta=True,
                null=True,
                quality=100,
                scale=None,
                size=[1920, 1080],
                upload_to="images",
            ),
        ),
    ]
